[package]
name = "rust_mergedirectories"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.120"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
wit-bindgen = "0.27.0"
